apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      type: string
      description: Nombre y tag de la imagen a construir (ej. quay.io/user/app:latest)
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
      description: Ruta al Dockerfile
    - name: CONTEXT
      type: string
      default: .
      description: Contexto de build
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.27.0
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Construyendo imagen con Buildah..."
        buildah bud \
          --layers \
          -f $(params.DOCKERFILE) \
          -t $(params.IMAGE) \
          $(params.CONTEXT)

    - name: push
      image: quay.io/buildah/stable:v1.27.0
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Pushing la imagen $(params.IMAGE)..."
        buildah push $(params.IMAGE)
